name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server
        env:
          SA_PASSWORD: 1q2w3e4r@#$
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433        
    steps:    
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Allow Remote Connectiosn to DB
        run: docker exec -it mssql /opt/mssql-tools/bin/sqlcmd \ -S localhost -U SA \ -Q "EXEC sp_configure 'remote access', 0; GO; RECONFIGURE; GO;"
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
