name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sqlserver:        
        image: mcr.microsoft.com/mssql/server
        env:
          SA_PASSWORD: 1q2w3e4r@#$
          ACCEPT_EULA: 'Y'
        ports:
          - 4433:1433        
    steps:
      - name: Set environment variable ENV_CONTAINER_ID
        run: echo "ENV_CONTAINER_ID=$(docker ps --all --filter status=running --no-trunc --format "{{.ID}}")" >> $GITHUB_ENV
      -
        name: Allow Remote Connections to DB
        run: docker exec -i $ENV_CONTAINER_ID /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "1q2w3e4r@#$" -Q "EXEC sp_configure 'remote access', 0; GO; RECONFIGURE; GO;"
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2     
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        run: docker-compose -f "docker-compose.yml" up -d --build
        with:          
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest      
      - 
        name: Run Migrations
        run: docker exec pb-clients_web_1 ./PB.Clients.Migration

