name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:     
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Run Docker Compose
        run: docker-compose -f "docker-compose.yml" up -d --build
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2     
      - 
        name: Build and push
        uses: docker/build-push-action@v4        
        with:          
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest      
      - 
        name: Run Migrations
        run: docker exec pb-clients_web_1 ./PB.Clients.Migration

