name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:     
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Run Docker Compose
        run: docker-compose -f "compose.yaml" up -d --build
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -      
        name: Run Migrations
        run: docker exec pb-clients_web_1 ./PB.Clients.Migration

